### ISSUE TITLE
Add osmapp.org

### ISSUE THREAD

**Issue by TheLimifiedLime** [osmlab/awesome-openstreetmap#111]
**Link To Project**
[Link to the project here](https://osmapp.org)

**Short description of the Project**
osmapp.org is a browsable map with OSM data along with the ability to help edit map features

**Why is it awesome?**
This is a bit different than other maps that allow you to view OSM data in a map as it both shows data and has the ability to edit it

**Additional Links**
[Source Code](https://github.com/zbycz/osmapp)

**Comments**
None

**Comment by Unkn0wnCat** [comment]
Thanks for your suggestion! The map looks awesome and is a great addition to the awesome-list 😃

**Comment by TheLimifiedLime** [comment]
No problem! I'm glad it's on the list now!
