### ISSUE TITLE
Add Earthwalker to Map Games

### ISSUE THREAD

**Issue by nodiscc** [osmlab/awesome-openstreetmap#112]
**Link To Project**
https://gitlab.com/glatteis/earthwalker

**Short description of the Project**
A GeoGuessr clone playable in browser. Find where you are in the world using only Google StreetView. Supports custom challenges and multiplayer.

**Why is it awesome?**
Supports OSM tileservers despite photographic/Street View data being served from Google Maps. Players may find it a suitable replacement for the non-Free https://www.geoguessr.com/ game. Developers may find it a good starting point to work on a Free street view alternative.

**Additional Links**
[Source Code](https://gitlab.com/glatteis/earthwalker)

**Comments**

Moved from https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2759, see comments there.

/cc @claabs

```
 - [Earthwalker](https://gitlab.com/glatteis/earthwalker) `⚠` - A GeoGuessr clone playable in browser. Find where you are in the world using only Google StreetView. Supports custom challenges and multiplayer. `GPL-3.0` `Go`
```

**Comment by Unkn0wnCat** [comment]
Hey @nodiscc,

thanks for your patience as I've not had the time to go after issues lately. Earthwalker really does look like an awesome alternative to playing Geoguessr, thanks for suggesting it (especially since our games category is still pretty bare 😛)!

**Comment by Unkn0wnCat** [comment]
I've just noticed the project does not use OpenStreetMap-data, but Google Maps data. Sadly I'll have to revert the addition, as we only collect OpenStreetMap-related projects. I'm sorry :(

**Comment by nodiscc** [comment]
The tileserver is configurable https://gitlab.com/glatteis/earthwalker#configuration and can be set up to use OSM data, but we had the same concern in https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2759, as street view imagery comes from Google.

**Comment by Unkn0wnCat** [comment]
Yeah... I saw the tileserver setting, but I feel adding a project which requires connection to a proprietary mapping service i.e. Google Maps / Google Street View goes against the spirit of the OpenStreetMap community
