### ISSUE TITLE
Add GeoGuess to Map Games

### ISSUE THREAD

**Issue by nodiscc** [osmlab/awesome-openstreetmap#113]
**Link To Project**
https://geoguess.games

**Short description of the Project**
Open-source geographic game with Google Map Street-View.

**Why is it awesome?**
 Supports OSM tileservers despite photographic/Street View data being served from Google Maps. Players may find it a suitable replacement for the non-Free https://www.geoguessr.com/ game. Developers may find it a good starting point to work on a Free street view alternative.

**Additional Links**
[Source Code](https://github.com/GeoGuess/GeoGuess)

**Comments**

Moved from https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2856, see comments at https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2759

/cc @BilelJegham

```
 - [GeoGuess](https://geoguess.games/) `⚠` - Open-source geographic game with Google Map Street-View. (singleplayer or multiplayer) ([Demo](https://demo.geoguess.games/) [Source Code](https://github.com/GeoGuess/GeoGuess)) `MIT` `Javascript`
```

**Comment by Unkn0wnCat** [comment]
Sadly, this too uses Google Maps, which makes it unsuitable for this list, I'm afraid :/
