### ISSUE TITLE
Add Tracesmap to Web Maps

### ISSUE THREAD

**Issue by strongwillow** [osmlab/awesome-openstreetmap#117]
**Link To Project**
https://tracesmap.com/

**Short description of the Project**
OsmCarto and OpenTopoMap-derived retina maps with multiple route and language label layers. Support search and navigation.

**Why is it awesome?**
It can be used to search for places and navigating between point-to-point. Overpass integration allows showing POI and place information.

**Additional Links**
[Source Code?]

**Comments**
[Any additional infos]

**Comment by Unkn0wnCat** [comment]
Thanks for the recommendation @strongwillow! 👍🏼
