### ISSUE TITLE
 Pull Request (PR) descriptions

### ISSUE THREAD

**Issue by papac25** [osmlab/awesome-openstreetmap#15]
#### Pull Request (PR) description
EXOSafeLinksPolicy: Added missing properties CustomNotificationText, EnableOrganizationBranding, UseTranslatedNotificationText

#### This Pull Request (PR) fixes the following issues
None

__Originally posted by @mpiederiet in https://github.com/microsoft/Microsoft365DSC/pull/1451__

**Comment by papac25** [comment]
> #### Pull Request (PR) description
> 
> EXOSafeLinksPolicy: Added missing properties CustomNotificationText, EnableOrganizationBranding, UseTranslatedNotificationText
> 
> 
> 
> #### This Pull Request (PR) fixes the following issues
> 
> None
> 
> 
> 
> __Originally posted by @mpiederiet in https://github.com/microsoft/Microsoft365DSC/pull/1451__

**Comment by Unkn0wnCat** [comment]
Hey @papac25,

it seems your issue has ended up in the wrong place. I'll be closing the issue, so if I am misjudging this, please reopen this issue and specify what exactly it is you mean by this! 🙂
