### ISSUE TITLE
Qwant Maps, Vespucci, & Discord

### ISSUE THREAD

**Issue by TheLimifiedLime** [osmlab/awesome-openstreetmap#24]
[Qwant Maps](https://www.qwant.com/maps) - Only real  web based Google Maps alternative using OSM data I've seen.

[Vespucci](https://vespucci.io) - Android only OSM editor. A bit more advanced but more powerful too.

There's also a [Discord server](https://discord.gg/openstreetmap)

I know of a few others too and I'll add them to this list/issue soon

**Comment by Unkn0wnCat** [comment]
Thanks!

I've gone ahead and added them, feel free to open another issue with more suggestions! 🙂
