### ISSUE TITLE
I heard good things about GoMap!! for Apple devices

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/awesome-openstreetmap#25]
tested for just minute, but seemed really nice

https://github.com/osmlab/awesome-openstreetmap#mobile-editors

**Comment by Unkn0wnCat** [comment]
Seems to be very well liked, and we are missing editors for iOS.
Thanks!

**Comment by habi** [comment]
It's awesome, I made about 20% of my changesets with it.

**Comment by Unkn0wnCat** [comment]
> It's awesome, I made about 20% of my changesets with it.

Nice, then we have an awesome editor for iOS now as well!
