### ISSUE TITLE
Add Several Projects

### ISSUE THREAD

**Issue by joelotz** [osmlab/awesome-openstreetmap#55]
**Link To Project**
[[Road Curvature]](https://roadcurvature.com/map/)

**Short description of the Project**
Curvature helps find curvy roads for those who enjoy them.

**Why is it awesome?**
Site analyzes the "twistiness" of roads for enjoyment by motorcycle or driving enthusiasts.

**Additional Links**
[[Source Code?]](https://roadcurvature.com/download-data/detected-curves/)

-------------------------------------------

**Link To Project**
[[Back Of Your Hand]](https://backofyourhand.com/)

**Short description of the Project**
A web map game that asks you to find a street in a given area. 

**Why is it awesome?**
It tests your knowledge of your local area by locating streets. 

------------------------------------------------

**Link To Project**
[[OnOSM]](https://www.onosm.org/)

**Short description of the Project**
Allows someone to submit business information for inclusion into OSM.

**Why is it awesome?**
Novice or non-OSM participants can submit information that will be entered as a note into OSM. Users can verify the information and add the business.

------------------------------------------------

**Link To Project**
[[OpenGeofiction]](https://opengeofiction.net/)

**Short description of the Project**
A user-made world map of a fictional world, created using the OSM software platform.

**Why is it awesome?**
Like OSM but entirely made-up by users.

**Comment by Unkn0wnCat** [comment]
Great projects! I'll go ahead and add them right away 🎉

**Comment by Unkn0wnCat** [comment]
And it's done! Thanks for your additions! 😃
