### ISSUE TITLE
Add editor plugins

### ISSUE THREAD

**Issue by danieldegroot2** [osmlab/awesome-openstreetmap#66]
_Open issue_

Add a section with editor plugins. (as of now, it may be restricted to JOSM plugins)

Look through [this wiki page](https://wiki.openstreetmap.org/wiki/JOSM/Plugins).

**Comment by Unkn0wnCat** [comment]
This list is not meant to be a complete list of everything. We try to collect projects a new OSM contributor/developer/user might find awesome. I think listing JOSM plugins / editor plugins does not fit with this goal and just make the list bloated and hard to navigate.

If you are passionate about JOSM I'd really encourage you to create a seperate awesome list (e.g. awesome-josm) where you explicitly list awesome things regarding JOSM. Head over to [sindresorhus/awesome](https://github.com/sindresorhus/awesome/blob/main/create-list.md) to find out more about creating an awesome-list! (Feel free to contact me if you have questions about the process and I'd be happy to help! 🙂)

**Comment by danieldegroot2** [comment]
The ones I had in mind would be iD RapiD (available in the editor itself) and JOSM BuildingTools, which _can_ be very helpful for mapping buildings. Unfortunately, the first is viewed negatively when used incorrectly (users still don't notice / ignore they can adjust buildings) and the second is considered hard to install / use (it includes more features than just square buildings). Users can still find these through the tasking manager (and not use it again after) and have square buildings 'by default' in JOSM respectively. Thanks for the reply.
