### ISSUE TITLE
Add Maplibre GL JS

### ISSUE THREAD

**Issue by ttomasz** [osmlab/awesome-openstreetmap#71]
**Link To Project**
https://maplibre.org/projects/#js

**Short description of the Project**
Web map library similar to Leaflet and OpenLayers but better. It's a fork of Mapbox GL JS.

**Why is it awesome?**
Best documentation of all web map libraries hands down. Just look at how many examples there are: https://maplibre.org/maplibre-gl-js-docs/example/

Fully supports vector tiles and mapbox (powerful) style language.

**Additional Links**
https://github.com/maplibre/maplibre-gl-js

**Comments**
Add to section https://github.com/osmlab/awesome-openstreetmap#javascript=

**Comment by Unkn0wnCat** [comment]
Wow! There are some really awesome examples in there.

I'll go ahead and add it! 🎉
