### ISSUE TITLE
Look through Quality Assurance tools page on OSM wiki

### ISSUE THREAD

**Issue by Woazboat** [osmlab/awesome-openstreetmap#79]
The [Quality Assurance](https://wiki.openstreetmap.org/wiki/Quality_assurance) page on the OSM wiki lists a bunch of tools which should be added to the list.

**Comment by chnuessli** [comment]
@Unkn0wnCat if you want, you can assign me. I'm currently on the job to search for cool QA Tools

**Comment by chnuessli** [comment]
@Woazboat Look at the listed PR. What do you think? Honestly i found not anymore good QA tools. Most of them already listed.
