### ISSUE TITLE
Add PraxisMapper

### ISSUE THREAD

**Issue by drakewill-CRL** [osmlab/awesome-openstreetmap#84]
**Link To Project**
[PraxisMapper](https://github.com/drakewill-CRL/PraxisMapper)

**Short description of the Project**
GPS Game server, for making mobile games around exploring the real world.

**Why is it awesome?**
People can use it to make games about going to real places. It handles drawing map tiles on its own. It scales up to continent sizes or down to a county that could run on a typical laptop. It's extremely customizable. There's a companion demo app called Hypothesis that includes a few example game ideas that could be built upon.

**Additional Links**
Source code is at original link.

**Comments**
Written in C#. Might be the only current C# project built to draw maptiles from OSM data. I'm the author of the project.

**Comment by Unkn0wnCat** [comment]
Which category do you think this fits best under? From looking at the project it looks like Libraries -> C# would be a good category. What do you think?

**Comment by drakewill-CRL** [comment]
Would it belong under Map Games instead? It's meant to be for games that use the map, and while you can use the core of it as a library, you can just run the executable to get a server going, and point the mobile app to that IP address to get a game up and running.

**Comment by Unkn0wnCat** [comment]
Ah so it is a fully working game in itself?

Sorry, I haven't quite understood what exactly the program does yet :(

**Comment by drakewill-CRL** [comment]
Yes, though the user has to provide the map data for it.
