### ISSUE TITLE
Add Every Door

### ISSUE THREAD

**Issue by DickerPeter** [osmlab/awesome-openstreetmap#91]
**Link To Project**
[Every Door - Projekt Webseite](https://every-door.app/)
[Every Door - OSM Wiki](https://wiki.openstreetmap.org/wiki/Every_Door)

**Short description of the Project**
[Every Door is an Android and iOS app that lets you create and edit objects in OpenStreetMap. It supports editing node and polygon features, and creating point features like shops, benches, and building entrances. The source code is published under the open ISC license on [GitHub](https://github.com/zverik/every_door).]

**Why is it awesome?**
[Mobile mappers could benefit from it.]

**Additional Links**
[Zverik Github](https://github.com/zverik/every_door)

**Comments**
[Any additional infos]

**Comment by joelotz** [comment]
I've submitted PR[#92](https://github.com/osmlab/awesome-openstreetmap/pull/92) to satisfy this request/issue.
